package com.gency.subscribe.model.business;

import com.gency.subscribe.model.base.BaseModel;
import java.util.Date;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2018-04-23 10:44:02
  */
public class AccAdviserBase extends BaseModel {
    /**
     * 数据编号
     * 表字段 : acc_adviser_base.id
     */
    private Long id;

    /**
     * 姓名
     * 表字段 : acc_adviser_base.name
     */
    private String name;

    /**
     * 置业顾问电话号码
     * 表字段 : acc_adviser_base.phone
     */
    private String phone;

    /**
     * 创建时间
     * 表字段 : acc_adviser_base.create_time
     */
    private Date createTime;

    /**
     * 1:正常 2:异常
     * 表字段 : acc_adviser_base.state
     */
    private Byte state;

    /**
     * 0:正常 1:删除
     * 表字段 : acc_adviser_base.is_delete
     */
    private Byte isDelete;

    /**
     * 置业顾问接单权重（值越大权重越大）
     * 表字段 : acc_adviser_base.order
     */
    private Integer order;

    /**
     * 冗余字段
     * 表字段 : acc_adviser_base.mark
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table acc_adviser_base
     *
     * @mbg.generated Mon Apr 23 10:44:02 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 数据编号 字段:acc_adviser_base.id
     *
     * @return acc_adviser_base.id, 数据编号
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置 数据编号 字段:acc_adviser_base.id
     *
     * @param id the value for acc_adviser_base.id, 数据编号
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 姓名 字段:acc_adviser_base.name
     *
     * @return acc_adviser_base.name, 姓名
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 姓名 字段:acc_adviser_base.name
     *
     * @param name the value for acc_adviser_base.name, 姓名
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 置业顾问电话号码 字段:acc_adviser_base.phone
     *
     * @return acc_adviser_base.phone, 置业顾问电话号码
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 设置 置业顾问电话号码 字段:acc_adviser_base.phone
     *
     * @param phone the value for acc_adviser_base.phone, 置业顾问电话号码
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * 获取 创建时间 字段:acc_adviser_base.create_time
     *
     * @return acc_adviser_base.create_time, 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:acc_adviser_base.create_time
     *
     * @param createTime the value for acc_adviser_base.create_time, 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 1:正常 2:异常 字段:acc_adviser_base.state
     *
     * @return acc_adviser_base.state, 1:正常 2:异常
     */
    public Byte getState() {
        return state;
    }

    /**
     * 设置 1:正常 2:异常 字段:acc_adviser_base.state
     *
     * @param state the value for acc_adviser_base.state, 1:正常 2:异常
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * 获取 0:正常 1:删除 字段:acc_adviser_base.is_delete
     *
     * @return acc_adviser_base.is_delete, 0:正常 1:删除
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * 设置 0:正常 1:删除 字段:acc_adviser_base.is_delete
     *
     * @param isDelete the value for acc_adviser_base.is_delete, 0:正常 1:删除
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * 获取 置业顾问接单权重（值越大权重越大） 字段:acc_adviser_base.order
     *
     * @return acc_adviser_base.order, 置业顾问接单权重（值越大权重越大）
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * 设置 置业顾问接单权重（值越大权重越大） 字段:acc_adviser_base.order
     *
     * @param order the value for acc_adviser_base.order, 置业顾问接单权重（值越大权重越大）
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * 获取 冗余字段 字段:acc_adviser_base.mark
     *
     * @return acc_adviser_base.mark, 冗余字段
     */
    public String getMark() {
        return mark;
    }

    /**
     * 设置 冗余字段 字段:acc_adviser_base.mark
     *
     * @param mark the value for acc_adviser_base.mark, 冗余字段
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }
}