package com.gency.subscribe.model.business;

import com.gency.subscribe.model.base.BaseModel;
import java.util.Date;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2018-04-26 22:07:51
  */
public class AdviserReceptionUser extends BaseModel {
    /**
     * 
     * 表字段 : adviser_reception_user.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : adviser_reception_user.adviser_id
     */
    private Integer adviserId;

    /**
     * 用户电话
     * 表字段 : adviser_reception_user.user_tel
     */
    private String userTel;
    
    
    private String userName;

    /**
     * 创建时间
     * 表字段 : adviser_reception_user.create_time
     */
    private Date createTime;

    /**
     * 1:未接待 2:已接待
     * 表字段 : adviser_reception_user.state
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adviser_reception_user
     *
     * @mbg.generated Thu Apr 26 22:07:51 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:adviser_reception_user.id
     *
     * @return adviser_reception_user.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:adviser_reception_user.id
     *
     * @param id the value for adviser_reception_user.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:adviser_reception_user.adviser_id
     *
     * @return adviser_reception_user.adviser_id, 
     */
    public Integer getAdviserId() {
        return adviserId;
    }

    /**
     * 设置  字段:adviser_reception_user.adviser_id
     *
     * @param adviserId the value for adviser_reception_user.adviser_id, 
     */
    public void setAdviserId(Integer adviserId) {
        this.adviserId = adviserId;
    }

    /**
     * 获取 用户电话 字段:adviser_reception_user.user_tel
     *
     * @return adviser_reception_user.user_tel, 用户电话
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * 设置 用户电话 字段:adviser_reception_user.user_tel
     *
     * @param userTel the value for adviser_reception_user.user_tel, 用户电话
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * 获取 创建时间 字段:adviser_reception_user.create_time
     *
     * @return adviser_reception_user.create_time, 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:adviser_reception_user.create_time
     *
     * @param createTime the value for adviser_reception_user.create_time, 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 1:未接待 2:已接待 字段:adviser_reception_user.state
     *
     * @return adviser_reception_user.state, 1:未接待 2:已接待
     */
    public Integer getState() {
        return state;
    }

    /**
     * 设置 1:未接待 2:已接待 字段:adviser_reception_user.state
     *
     * @param state the value for adviser_reception_user.state, 1:未接待 2:已接待
     */
    public void setState(Integer state) {
        this.state = state;
    }

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
    
    
}