package com.gency.subscribe.model.business;

import javax.validation.constraints.NotEmpty;

import org.hibernate.validator.constraints.Length;

import com.gency.subscribe.model.base.BaseModel;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2018-04-23 10:44:37
  */
public class Goods extends BaseModel {
    /**
     * 数据编号
     * 表字段 : goods.id
     */
    private Integer id;

    /**
     * 商品类型
     * 表字段 : goods.type_id
     */
    private Integer typeId;

    /**
     * 商品名称
     * 表字段 : goods.name
     */
    @NotEmpty(message="商品名称不能为空")
    @Length(max=30,message="商品名称不能太长")
    private String name;

    /**
     * 商品价格
     * 表字段 : goods.price
     */
    @NotEmpty(message="商品价格不能为空")
    @Length(max=30,message="商品价格太大")
    private String price;

    /**
     * 0:正常 1:删除
     * 表字段 : goods.is_delete
     */
    private Byte isDelete;
    
    private String num;
    
    

    public String getNum() {
		return num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbg.generated Mon Apr 23 10:44:37 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 数据编号 字段:goods.id
     *
     * @return goods.id, 数据编号
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 数据编号 字段:goods.id
     *
     * @param id the value for goods.id, 数据编号
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 商品类型 字段:goods.type_id
     *
     * @return goods.type_id, 商品类型
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * 设置 商品类型 字段:goods.type_id
     *
     * @param typeId the value for goods.type_id, 商品类型
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * 获取 商品名称 字段:goods.name
     *
     * @return goods.name, 商品名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 商品名称 字段:goods.name
     *
     * @param name the value for goods.name, 商品名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 商品价格 字段:goods.price
     *
     * @return goods.price, 商品价格
     */
    public String getPrice() {
        return price;
    }

    /**
     * 设置 商品价格 字段:goods.price
     *
     * @param price the value for goods.price, 商品价格
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * 获取 0:正常 1:删除 字段:goods.is_delete
     *
     * @return goods.is_delete, 0:正常 1:删除
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * 设置 0:正常 1:删除 字段:goods.is_delete
     *
     * @param isDelete the value for goods.is_delete, 0:正常 1:删除
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}