package com.gency.subscribe.model.business;

import com.gency.subscribe.model.base.BaseModel;
import java.util.Date;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2018-04-24 21:22:40
  */
public class SerUserBase extends BaseModel {
    /**
     * 数据编号
     * 表字段 : ser_user_base.id
     */
    private Long id;

    /**
     * 创建时间
     * 表字段 : ser_user_base.create_time
     */
    private Date createTime;

    /**
     * 桌子号
     * 表字段 : ser_user_base.tables_number
     */
    private String tablesNumber;

    /**
     * 关联商品数据Id
     * 表字段 : ser_user_base.goods_info
     */
    private String goodsInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ser_user_base
     *
     * @mbg.generated Tue Apr 24 21:22:40 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 数据编号 字段:ser_user_base.id
     *
     * @return ser_user_base.id, 数据编号
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置 数据编号 字段:ser_user_base.id
     *
     * @param id the value for ser_user_base.id, 数据编号
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 创建时间 字段:ser_user_base.create_time
     *
     * @return ser_user_base.create_time, 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:ser_user_base.create_time
     *
     * @param createTime the value for ser_user_base.create_time, 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 桌子号 字段:ser_user_base.tables_number
     *
     * @return ser_user_base.tables_number, 桌子号
     */
    public String getTablesNumber() {
        return tablesNumber;
    }

    /**
     * 设置 桌子号 字段:ser_user_base.tables_number
     *
     * @param tablesNumber the value for ser_user_base.tables_number, 桌子号
     */
    public void setTablesNumber(String tablesNumber) {
        this.tablesNumber = tablesNumber == null ? null : tablesNumber.trim();
    }

    /**
     * 获取 关联商品数据Id 字段:ser_user_base.goods_info
     *
     * @return ser_user_base.goods_info, 关联商品数据Id
     */
    public String getGoodsInfo() {
        return goodsInfo;
    }

    /**
     * 设置 关联商品数据Id 字段:ser_user_base.goods_info
     *
     * @param goodsInfo the value for ser_user_base.goods_info, 关联商品数据Id
     */
    public void setGoodsInfo(String goodsInfo) {
        this.goodsInfo = goodsInfo == null ? null : goodsInfo.trim();
    }
}