package com.gency.subscribe.model.business;

import com.gency.subscribe.model.base.BaseModel;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2018-04-23 10:46:09
  */
public class SerUserCall extends BaseModel {
    /**
     * 数据编号
     * 表字段 : ser_user_call.id
     */
    private Long id;

    /**
     * 关联用户数据
     * 表字段 : ser_user_call.user_id
     */
    private Long userId;

    /**
     * 桌号
     * 表字段 : ser_user_call.table_number
     */
    private String tableNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ser_user_call
     *
     * @mbg.generated Mon Apr 23 10:46:09 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 数据编号 字段:ser_user_call.id
     *
     * @return ser_user_call.id, 数据编号
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置 数据编号 字段:ser_user_call.id
     *
     * @param id the value for ser_user_call.id, 数据编号
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 关联用户数据 字段:ser_user_call.user_id
     *
     * @return ser_user_call.user_id, 关联用户数据
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * 设置 关联用户数据 字段:ser_user_call.user_id
     *
     * @param userId the value for ser_user_call.user_id, 关联用户数据
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 获取 桌号 字段:ser_user_call.table_number
     *
     * @return ser_user_call.table_number, 桌号
     */
    public String getTableNumber() {
        return tableNumber;
    }

    /**
     * 设置 桌号 字段:ser_user_call.table_number
     *
     * @param tableNumber the value for ser_user_call.table_number, 桌号
     */
    public void setTableNumber(String tableNumber) {
        this.tableNumber = tableNumber == null ? null : tableNumber.trim();
    }
}