package com.gency.subscribe.model.business;

import com.gency.subscribe.model.base.BaseModel;
import java.util.Date;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2018-04-23 10:45:49
  */
public class SerUserBase extends BaseModel {
    /**
     * 数据编号
     * 表字段 : ser_user_base.id
     */
    private Long id;

    /**
     * 创建时间
     * 表字段 : ser_user_base.create_time
     */
    private Date createTime;

    /**
     * 桌子号
     * 表字段 : ser_user_base.tables_number
     */
    private String tablesNumber;

    /**
     * 关联商品数据Id
     * 表字段 : ser_user_base.goods_id
     */
    private Long goodsId;

    /**
     * 商品数量
     * 表字段 : ser_user_base.number
     */
    private Integer number;

    /**
     * 关联用户id
     * 表字段 : ser_user_base.reg_id
     */
    private Long regId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ser_user_base
     *
     * @mbg.generated Mon Apr 23 10:45:49 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 数据编号 字段:ser_user_base.id
     *
     * @return ser_user_base.id, 数据编号
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置 数据编号 字段:ser_user_base.id
     *
     * @param id the value for ser_user_base.id, 数据编号
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 创建时间 字段:ser_user_base.create_time
     *
     * @return ser_user_base.create_time, 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:ser_user_base.create_time
     *
     * @param createTime the value for ser_user_base.create_time, 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 桌子号 字段:ser_user_base.tables_number
     *
     * @return ser_user_base.tables_number, 桌子号
     */
    public String getTablesNumber() {
        return tablesNumber;
    }

    /**
     * 设置 桌子号 字段:ser_user_base.tables_number
     *
     * @param tablesNumber the value for ser_user_base.tables_number, 桌子号
     */
    public void setTablesNumber(String tablesNumber) {
        this.tablesNumber = tablesNumber == null ? null : tablesNumber.trim();
    }

    /**
     * 获取 关联商品数据Id 字段:ser_user_base.goods_id
     *
     * @return ser_user_base.goods_id, 关联商品数据Id
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * 设置 关联商品数据Id 字段:ser_user_base.goods_id
     *
     * @param goodsId the value for ser_user_base.goods_id, 关联商品数据Id
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * 获取 商品数量 字段:ser_user_base.number
     *
     * @return ser_user_base.number, 商品数量
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * 设置 商品数量 字段:ser_user_base.number
     *
     * @param number the value for ser_user_base.number, 商品数量
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * 获取 关联用户id 字段:ser_user_base.reg_id
     *
     * @return ser_user_base.reg_id, 关联用户id
     */
    public Long getRegId() {
        return regId;
    }

    /**
     * 设置 关联用户id 字段:ser_user_base.reg_id
     *
     * @param regId the value for ser_user_base.reg_id, 关联用户id
     */
    public void setRegId(Long regId) {
        this.regId = regId;
    }
}