package com.gency.subscribe.model.business;

import com.gency.subscribe.model.base.BaseModel;
import java.util.Date;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2018-04-24 21:42:01
  */
public class SerUserCall extends BaseModel {
    /**
     * 数据编号
     * 表字段 : ser_user_call.id
     */
    private Long id;

    /**
     * 呼叫时间
     * 表字段 : ser_user_call.create_time
     */
    private Date createTime;

    /**
     * 桌号
     * 表字段 : ser_user_call.table_number
     */
    private String tableNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ser_user_call
     *
     * @mbg.generated Tue Apr 24 21:42:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 数据编号 字段:ser_user_call.id
     *
     * @return ser_user_call.id, 数据编号
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置 数据编号 字段:ser_user_call.id
     *
     * @param id the value for ser_user_call.id, 数据编号
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 呼叫时间 字段:ser_user_call.create_time
     *
     * @return ser_user_call.create_time, 呼叫时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 呼叫时间 字段:ser_user_call.create_time
     *
     * @param createTime the value for ser_user_call.create_time, 呼叫时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 桌号 字段:ser_user_call.table_number
     *
     * @return ser_user_call.table_number, 桌号
     */
    public String getTableNumber() {
        return tableNumber;
    }

    /**
     * 设置 桌号 字段:ser_user_call.table_number
     *
     * @param tableNumber the value for ser_user_call.table_number, 桌号
     */
    public void setTableNumber(String tableNumber) {
        this.tableNumber = tableNumber == null ? null : tableNumber.trim();
    }
}