package com.gency.subscribe.model.business;

import com.gency.subscribe.model.base.BaseModel;
import java.util.Date;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2018-04-23 10:46:36
  */
public class TraOrderBase extends BaseModel {
    /**
     * 数据编号
     * 表字段 : tra_order_base.order_no
     */
    private Long orderNo;

    /**
     * 创建时间
     * 表字段 : tra_order_base.create_time
     */
    private Date createTime;

    /**
     * 关联用户注册表Id
     * 表字段 : tra_order_base.reg_id
     */
    private Long regId;

    /**
     * 0:预约 1:已到访
     * 表字段 : tra_order_base.state
     */
    private Byte state;

    /**
     * 车牌号
     * 表字段 : tra_order_base.license_plate
     */
    private String licensePlate;

    /**
     * 到访人数
     * 表字段 : tra_order_base.number_of_people
     */
    private Integer numberOfPeople;

    /**
     * 到访日期
     * 表字段 : tra_order_base.date_of_visit
     */
    private String dateOfVisit;

    /**
     * 1:上午 2:下午
     * 表字段 : tra_order_base.morning_or_afternoon
     */
    private Byte morningOrAfternoon;

    /**
     * 冗余用户手机号码
     * 表字段 : tra_order_base.user_phone
     */
    private String userPhone;

    /**
     * 置业顾问数据Id
     * 表字段 : tra_order_base.adviser_id
     */
    private Long adviserId;

    /**
     * 置业顾问电话号码
     * 表字段 : tra_order_base.adviser_phone
     */
    private String adviserPhone;

    /**
     * 订单备注
     * 表字段 : tra_order_base.mark
     */
    private String mark;

    /**
     * 订单确认时间
     * 表字段 : tra_order_base.confirm_time
     */
    private Date confirmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tra_order_base
     *
     * @mbg.generated Mon Apr 23 10:46:36 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 数据编号 字段:tra_order_base.order_no
     *
     * @return tra_order_base.order_no, 数据编号
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * 设置 数据编号 字段:tra_order_base.order_no
     *
     * @param orderNo the value for tra_order_base.order_no, 数据编号
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * 获取 创建时间 字段:tra_order_base.create_time
     *
     * @return tra_order_base.create_time, 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:tra_order_base.create_time
     *
     * @param createTime the value for tra_order_base.create_time, 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 关联用户注册表Id 字段:tra_order_base.reg_id
     *
     * @return tra_order_base.reg_id, 关联用户注册表Id
     */
    public Long getRegId() {
        return regId;
    }

    /**
     * 设置 关联用户注册表Id 字段:tra_order_base.reg_id
     *
     * @param regId the value for tra_order_base.reg_id, 关联用户注册表Id
     */
    public void setRegId(Long regId) {
        this.regId = regId;
    }

    /**
     * 获取 0:预约 1:已到访 字段:tra_order_base.state
     *
     * @return tra_order_base.state, 0:预约 1:已到访
     */
    public Byte getState() {
        return state;
    }

    /**
     * 设置 0:预约 1:已到访 字段:tra_order_base.state
     *
     * @param state the value for tra_order_base.state, 0:预约 1:已到访
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * 获取 车牌号 字段:tra_order_base.license_plate
     *
     * @return tra_order_base.license_plate, 车牌号
     */
    public String getLicensePlate() {
        return licensePlate;
    }

    /**
     * 设置 车牌号 字段:tra_order_base.license_plate
     *
     * @param licensePlate the value for tra_order_base.license_plate, 车牌号
     */
    public void setLicensePlate(String licensePlate) {
        this.licensePlate = licensePlate == null ? null : licensePlate.trim();
    }

    /**
     * 获取 到访人数 字段:tra_order_base.number_of_people
     *
     * @return tra_order_base.number_of_people, 到访人数
     */
    public Integer getNumberOfPeople() {
        return numberOfPeople;
    }

    /**
     * 设置 到访人数 字段:tra_order_base.number_of_people
     *
     * @param numberOfPeople the value for tra_order_base.number_of_people, 到访人数
     */
    public void setNumberOfPeople(Integer numberOfPeople) {
        this.numberOfPeople = numberOfPeople;
    }

    /**
     * 获取 到访日期 字段:tra_order_base.date_of_visit
     *
     * @return tra_order_base.date_of_visit, 到访日期
     */
    public String getDateOfVisit() {
        return dateOfVisit;
    }

    /**
     * 设置 到访日期 字段:tra_order_base.date_of_visit
     *
     * @param dateOfVisit the value for tra_order_base.date_of_visit, 到访日期
     */
    public void setDateOfVisit(String dateOfVisit) {
        this.dateOfVisit = dateOfVisit == null ? null : dateOfVisit.trim();
    }

    /**
     * 获取 1:上午 2:下午 字段:tra_order_base.morning_or_afternoon
     *
     * @return tra_order_base.morning_or_afternoon, 1:上午 2:下午
     */
    public Byte getMorningOrAfternoon() {
        return morningOrAfternoon;
    }

    /**
     * 设置 1:上午 2:下午 字段:tra_order_base.morning_or_afternoon
     *
     * @param morningOrAfternoon the value for tra_order_base.morning_or_afternoon, 1:上午 2:下午
     */
    public void setMorningOrAfternoon(Byte morningOrAfternoon) {
        this.morningOrAfternoon = morningOrAfternoon;
    }

    /**
     * 获取 冗余用户手机号码 字段:tra_order_base.user_phone
     *
     * @return tra_order_base.user_phone, 冗余用户手机号码
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * 设置 冗余用户手机号码 字段:tra_order_base.user_phone
     *
     * @param userPhone the value for tra_order_base.user_phone, 冗余用户手机号码
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * 获取 置业顾问数据Id 字段:tra_order_base.adviser_id
     *
     * @return tra_order_base.adviser_id, 置业顾问数据Id
     */
    public Long getAdviserId() {
        return adviserId;
    }

    /**
     * 设置 置业顾问数据Id 字段:tra_order_base.adviser_id
     *
     * @param adviserId the value for tra_order_base.adviser_id, 置业顾问数据Id
     */
    public void setAdviserId(Long adviserId) {
        this.adviserId = adviserId;
    }

    /**
     * 获取 置业顾问电话号码 字段:tra_order_base.adviser_phone
     *
     * @return tra_order_base.adviser_phone, 置业顾问电话号码
     */
    public String getAdviserPhone() {
        return adviserPhone;
    }

    /**
     * 设置 置业顾问电话号码 字段:tra_order_base.adviser_phone
     *
     * @param adviserPhone the value for tra_order_base.adviser_phone, 置业顾问电话号码
     */
    public void setAdviserPhone(String adviserPhone) {
        this.adviserPhone = adviserPhone == null ? null : adviserPhone.trim();
    }

    /**
     * 获取 订单备注 字段:tra_order_base.mark
     *
     * @return tra_order_base.mark, 订单备注
     */
    public String getMark() {
        return mark;
    }

    /**
     * 设置 订单备注 字段:tra_order_base.mark
     *
     * @param mark the value for tra_order_base.mark, 订单备注
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * 获取 订单确认时间 字段:tra_order_base.confirm_time
     *
     * @return tra_order_base.confirm_time, 订单确认时间
     */
    public Date getConfirmTime() {
        return confirmTime;
    }

    /**
     * 设置 订单确认时间 字段:tra_order_base.confirm_time
     *
     * @param confirmTime the value for tra_order_base.confirm_time, 订单确认时间
     */
    public void setConfirmTime(Date confirmTime) {
        this.confirmTime = confirmTime;
    }
}