package com.gency.subscribe.model.business;

import com.gency.subscribe.model.base.BaseModel;
import java.util.Date;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2018-04-23 10:45:25
  */
public class UserUeg extends BaseModel {
    /**
     * 数据编号
     * 表字段 : reg_user_reg.reg_id
     */
    private Long regId;

    /**
     * 创建时间
     * 表字段 : reg_user_reg.reg_time
     */
    private Date regTime;

    /**
     * 电话号码
     * 表字段 : reg_user_reg.phone
     */
    private String phone;

    /**
     * 姓名
     * 表字段 : reg_user_reg.reg_name
     */
    private String regName;

    /**
     * 冗余字段
     * 表字段 : reg_user_reg.reg_mark
     */
    private String regMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reg_user_reg
     *
     * @mbg.generated Mon Apr 23 10:45:25 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 数据编号 字段:reg_user_reg.reg_id
     *
     * @return reg_user_reg.reg_id, 数据编号
     */
    public Long getRegId() {
        return regId;
    }

    /**
     * 设置 数据编号 字段:reg_user_reg.reg_id
     *
     * @param regId the value for reg_user_reg.reg_id, 数据编号
     */
    public void setRegId(Long regId) {
        this.regId = regId;
    }

    /**
     * 获取 创建时间 字段:reg_user_reg.reg_time
     *
     * @return reg_user_reg.reg_time, 创建时间
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * 设置 创建时间 字段:reg_user_reg.reg_time
     *
     * @param regTime the value for reg_user_reg.reg_time, 创建时间
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * 获取 电话号码 字段:reg_user_reg.phone
     *
     * @return reg_user_reg.phone, 电话号码
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 设置 电话号码 字段:reg_user_reg.phone
     *
     * @param phone the value for reg_user_reg.phone, 电话号码
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * 获取 姓名 字段:reg_user_reg.reg_name
     *
     * @return reg_user_reg.reg_name, 姓名
     */
    public String getRegName() {
        return regName;
    }

    /**
     * 设置 姓名 字段:reg_user_reg.reg_name
     *
     * @param regName the value for reg_user_reg.reg_name, 姓名
     */
    public void setRegName(String regName) {
        this.regName = regName == null ? null : regName.trim();
    }

    /**
     * 获取 冗余字段 字段:reg_user_reg.reg_mark
     *
     * @return reg_user_reg.reg_mark, 冗余字段
     */
    public String getRegMark() {
        return regMark;
    }

    /**
     * 设置 冗余字段 字段:reg_user_reg.reg_mark
     *
     * @param regMark the value for reg_user_reg.reg_mark, 冗余字段
     */
    public void setRegMark(String regMark) {
        this.regMark = regMark == null ? null : regMark.trim();
    }
}