package com.gency.subscribe.model.system;


/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2017-08-03 16:33:50
  */
public class AdminRole {
    /**
     * 主键
     * 表字段 : manage_admin_role.id
     */
    private Integer id;

    /**
     * 管理员数据Id
     * 表字段 : manage_admin_role.adminId
     */
    private Integer adminid;

    /**
     * 角色数据Id
     * 表字段 : manage_admin_role.roleId
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manage_admin_role
     *
     * @mbg.generated Thu Aug 03 16:33:50 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:manage_admin_role.id
     *
     * @return manage_admin_role.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:manage_admin_role.id
     *
     * @param id the value for manage_admin_role.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 管理员数据Id 字段:manage_admin_role.adminId
     *
     * @return manage_admin_role.adminId, 管理员数据Id
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * 设置 管理员数据Id 字段:manage_admin_role.adminId
     *
     * @param adminid the value for manage_admin_role.adminId, 管理员数据Id
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * 获取 角色数据Id 字段:manage_admin_role.roleId
     *
     * @return manage_admin_role.roleId, 角色数据Id
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * 设置 角色数据Id 字段:manage_admin_role.roleId
     *
     * @param roleid the value for manage_admin_role.roleId, 角色数据Id
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}