package com.gency.subscribe.model.system;

import java.util.Date;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import com.gency.subscribe.model.base.BaseModel;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2017-08-24 10:06:03
  */
public class ManageAuthority extends BaseModel {
    /**
     * 权限数据Id
     * 表字段 : manage_authority.id
     */
    private Integer id;

    /**
     * 数据编号
     * 表字段 : manage_authority.number
     */
    private String number;

    /**
     * 创建时间
     * 表字段 : manage_authority.createtime
     */
    private Date createtime;

    /**
     * 创建人
     * 表字段 : manage_authority.createadmin
     */
    private Integer createadmin;

    /**
     * 权限名称
     * 表字段 : manage_authority.authorityname
     */
    @NotEmpty(message="权限名称不能为空")
    @Length(max=100,message="权限名称太长")
    private String authorityname;

    /**
     * 权限路径
     * 表字段 : manage_authority.authorityurl
     */
    @NotEmpty(message="权限路径不能为空")
    @Length(max=200,message="权限路径太长")
    private String authorityurl;

    /**
     * 权限描述
     * 表字段 : manage_authority.authoritydescribe
     */
    @Length(max=255,message="权限描述信息太长")
    private String authoritydescribe;

    /**
     * 0:不开启日志记录 1:开启日志记录
     * 表字段 : manage_authority.authoritylogstate
     */
    private Integer authoritylogstate;

    /**
     * 所属菜单
     * 表字段 : manage_authority.menuId
     */
    private Integer menuid;

    /**
     * 0:否 1:是
     * 表字段 : manage_authority.isDelete
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manage_authority
     *
     * @mbg.generated Thu Aug 24 10:06:03 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 权限数据Id 字段:manage_authority.id
     *
     * @return manage_authority.id, 权限数据Id
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 权限数据Id 字段:manage_authority.id
     *
     * @param id the value for manage_authority.id, 权限数据Id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 数据编号 字段:manage_authority.number
     *
     * @return manage_authority.number, 数据编号
     */
    public String getNumber() {
        return number;
    }

    /**
     * 设置 数据编号 字段:manage_authority.number
     *
     * @param number the value for manage_authority.number, 数据编号
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * 获取 创建时间 字段:manage_authority.createtime
     *
     * @return manage_authority.createtime, 创建时间
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * 设置 创建时间 字段:manage_authority.createtime
     *
     * @param createtime the value for manage_authority.createtime, 创建时间
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * 获取 创建人 字段:manage_authority.createadmin
     *
     * @return manage_authority.createadmin, 创建人
     */
    public Integer getCreateadmin() {
        return createadmin;
    }

    /**
     * 设置 创建人 字段:manage_authority.createadmin
     *
     * @param createadmin the value for manage_authority.createadmin, 创建人
     */
    public void setCreateadmin(Integer createadmin) {
        this.createadmin = createadmin;
    }

    /**
     * 获取 权限名称 字段:manage_authority.authorityname
     *
     * @return manage_authority.authorityname, 权限名称
     */
    public String getAuthorityname() {
        return authorityname;
    }

    /**
     * 设置 权限名称 字段:manage_authority.authorityname
     *
     * @param authorityname the value for manage_authority.authorityname, 权限名称
     */
    public void setAuthorityname(String authorityname) {
        this.authorityname = authorityname == null ? null : authorityname.trim();
    }

    /**
     * 获取 权限路径 字段:manage_authority.authorityurl
     *
     * @return manage_authority.authorityurl, 权限路径
     */
    public String getAuthorityurl() {
        return authorityurl;
    }

    /**
     * 设置 权限路径 字段:manage_authority.authorityurl
     *
     * @param authorityurl the value for manage_authority.authorityurl, 权限路径
     */
    public void setAuthorityurl(String authorityurl) {
        this.authorityurl = authorityurl == null ? null : authorityurl.trim();
    }

    /**
     * 获取 权限描述 字段:manage_authority.authoritydescribe
     *
     * @return manage_authority.authoritydescribe, 权限描述
     */
    public String getAuthoritydescribe() {
        return authoritydescribe;
    }

    /**
     * 设置 权限描述 字段:manage_authority.authoritydescribe
     *
     * @param authoritydescribe the value for manage_authority.authoritydescribe, 权限描述
     */
    public void setAuthoritydescribe(String authoritydescribe) {
        this.authoritydescribe = authoritydescribe == null ? null : authoritydescribe.trim();
    }

    /**
     * 获取 0:不开启日志记录 1:开启日志记录 字段:manage_authority.authoritylogstate
     *
     * @return manage_authority.authoritylogstate, 0:不开启日志记录 1:开启日志记录
     */
    public Integer getAuthoritylogstate() {
        return authoritylogstate;
    }

    /**
     * 设置 0:不开启日志记录 1:开启日志记录 字段:manage_authority.authoritylogstate
     *
     * @param authoritylogstate the value for manage_authority.authoritylogstate, 0:不开启日志记录 1:开启日志记录
     */
    public void setAuthoritylogstate(Integer authoritylogstate) {
        this.authoritylogstate = authoritylogstate;
    }

    /**
     * 获取 所属菜单 字段:manage_authority.menuId
     *
     * @return manage_authority.menuId, 所属菜单
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * 设置 所属菜单 字段:manage_authority.menuId
     *
     * @param menuid the value for manage_authority.menuId, 所属菜单
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * 获取 0:否 1:是 字段:manage_authority.isDelete
     *
     * @return manage_authority.isDelete, 0:否 1:是
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * 设置 0:否 1:是 字段:manage_authority.isDelete
     *
     * @param isdelete the value for manage_authority.isDelete, 0:否 1:是
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}