package com.gency.subscribe.model.system;

import java.util.Date;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import com.gency.subscribe.model.base.BaseModel;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2017-08-24 12:01:11
  */
public class ManageRole extends BaseModel {
    /**
     * 角色数据Id
     * 表字段 : manage_role.id
     */
    private Integer id;

    /**
     * 数据编号
     * 表字段 : manage_role.number
     */
    private String number;

    /**
     * 创建时间
     * 表字段 : manage_role.createtime
     */
    private Date createtime;

    /**
     * 创建人
     * 表字段 : manage_role.createadmin
     */
    private Integer createadmin;

    /**
     * 角色名称
     * 表字段 : manage_role.rolename
     */
    @NotEmpty(message="角色名称不能为空")
    @Length(max=50,message="角色名称太长")
    private String rolename;

    /**
     * 角色描述
     * 表字段 : manage_role.roledescribe
     */
    private String roledescribe;

    /**
     * 0:普通 1:超级角色
     * 表字段 : manage_role.roletype
     */
    private Integer roletype;

    /**
     * 0:否 1:是
     * 表字段 : manage_role.isDelete
     */
    private Integer isdelete;
    
    
    public  Integer [] choseMenu;//选择的菜单集合
    
    public Integer [] choseAuthor;//选择的权限集合

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manage_role
     *
     * @mbg.generated Thu Aug 24 12:01:11 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 角色数据Id 字段:manage_role.id
     *
     * @return manage_role.id, 角色数据Id
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 角色数据Id 字段:manage_role.id
     *
     * @param id the value for manage_role.id, 角色数据Id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 数据编号 字段:manage_role.number
     *
     * @return manage_role.number, 数据编号
     */
    public String getNumber() {
        return number;
    }

    /**
     * 设置 数据编号 字段:manage_role.number
     *
     * @param number the value for manage_role.number, 数据编号
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * 获取 创建时间 字段:manage_role.createtime
     *
     * @return manage_role.createtime, 创建时间
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * 设置 创建时间 字段:manage_role.createtime
     *
     * @param createtime the value for manage_role.createtime, 创建时间
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * 获取 创建人 字段:manage_role.createadmin
     *
     * @return manage_role.createadmin, 创建人
     */
    public Integer getCreateadmin() {
        return createadmin;
    }

    /**
     * 设置 创建人 字段:manage_role.createadmin
     *
     * @param createadmin the value for manage_role.createadmin, 创建人
     */
    public void setCreateadmin(Integer createadmin) {
        this.createadmin = createadmin;
    }

    /**
     * 获取 角色名称 字段:manage_role.rolename
     *
     * @return manage_role.rolename, 角色名称
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * 设置 角色名称 字段:manage_role.rolename
     *
     * @param rolename the value for manage_role.rolename, 角色名称
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * 获取 角色描述 字段:manage_role.roledescribe
     *
     * @return manage_role.roledescribe, 角色描述
     */
    public String getRoledescribe() {
        return roledescribe;
    }

    /**
     * 设置 角色描述 字段:manage_role.roledescribe
     *
     * @param roledescribe the value for manage_role.roledescribe, 角色描述
     */
    public void setRoledescribe(String roledescribe) {
        this.roledescribe = roledescribe == null ? null : roledescribe.trim();
    }

    /**
     * 获取 0:普通 1:超级角色 字段:manage_role.roletype
     *
     * @return manage_role.roletype, 0:普通 1:超级角色
     */
    public Integer getRoletype() {
        return roletype;
    }
    
    /**
     * 设置 0:普通 1:超级角色 字段:manage_role.roletype
     *
     * @param roletype the value for manage_role.roletype, 0:普通 1:超级角色
     */
    public void setRoletype(Integer roletype) {
        this.roletype = roletype;
    }

    /**
     * 获取 0:否 1:是 字段:manage_role.isDelete
     *
     * @return manage_role.isDelete, 0:否 1:是
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * 设置 0:否 1:是 字段:manage_role.isDelete
     *
     * @param isdelete the value for manage_role.isDelete, 0:否 1:是
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

	public Integer[] getChoseMenu() {
		return choseMenu;
	}

	public void setChoseMenu(Integer[] choseMenu) {
		this.choseMenu = choseMenu;
	}

	public Integer[] getChoseAuthor() {
		return choseAuthor;
	}

	public void setChoseAuthor(Integer[] choseAuthor) {
		this.choseAuthor = choseAuthor;
	}
    
    
}