package com.gency.subscribe.model.system;

import java.util.Date;

import com.gency.subscribe.model.base.BaseModel;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2017-09-06 11:55:54
  */
public class OnlineSign extends BaseModel {
    /**
     * 主键ID
     * 表字段 : ec_online_sign.id
     */
    private Integer id;

    /**
     * 合作方式，佣金收取比例
     * 表字段 : ec_online_sign.cooperateType
     */
    private String cooperatetype;

    /**
     * 餐厅名字
     * 表字段 : ec_online_sign.restaurantName
     */
    private String restaurantname;

    /**
     * 餐厅类别
     * 表字段 : ec_online_sign.restaurantType
     */
    private String restauranttype;

    /**
     * 餐厅所在省
     * 表字段 : ec_online_sign.restaurantProvince
     */
    private String restaurantprovince;

    /**
     * 餐厅所在城市
     * 表字段 : ec_online_sign.restaurantCity
     */
    private String restaurantcity;

    /**
     * 餐厅所在区
     * 表字段 : ec_online_sign.restaurantDistrict
     */
    private String restaurantdistrict;

    /**
     * 餐厅所在街道
     * 表字段 : ec_online_sign.restaurantStreet
     */
    private String restaurantstreet;

    /**
     * 餐厅所在详细地址
     * 表字段 : ec_online_sign.restaurantAddress
     */
    private String restaurantaddress;

    /**
     * 餐厅电话
     * 表字段 : ec_online_sign.restaurantTel
     */
    private String restauranttel;

    /**
     * 
     * 表字段 : ec_online_sign.restaurantOpenTime
     */
    private String restaurantopentime;

    /**
     * 
     * 表字段 : ec_online_sign.restaurantCloseTime
     */
    private String restaurantclosetime;

    /**
     * 
     * 表字段 : ec_online_sign.restaurantIndroduction
     */
    private String restaurantindroduction;

    /**
     * 
     * 表字段 : ec_online_sign.managerPhone
     */
    private String managerphone;

    /**
     * 
     * 表字段 : ec_online_sign.bossPhone
     */
    private String bossphone;

    /**
     * 法人身份证号码
     * 表字段 : ec_online_sign.artificialPersonID
     */
    private String artificialpersonid;

    /**
     * 法人名字
     * 表字段 : ec_online_sign.artificialPersonName
     */
    private String artificialpersonname;

    /**
     * 
     * 表字段 : ec_online_sign.contractID
     */
    private String contractid;

    /**
     * 
     * 表字段 : ec_online_sign.contractName
     */
    private String contractname;

    /**
     * 
     * 表字段 : ec_online_sign.licenseID
     */
    private String licenseid;

    /**
     * 
     * 表字段 : ec_online_sign.licenseName
     */
    private String licensename;

    /**
     * 存放图片文件夹
     * 表字段 : ec_online_sign.baseURL
     */
    private String baseurl;

    /**
     * 餐厅图片
     * 表字段 : ec_online_sign.viewURL
     */
    private String viewurl;

    /**
     * 法人图片地址
     * 表字段 : ec_online_sign.artificialPersonURL
     */
    private String artificialpersonurl;

    /**
     * 
     * 表字段 : ec_online_sign.licenseURL
     */
    private String licenseurl;

    /**
     * 
     * 表字段 : ec_online_sign.contractURL
     */
    private String contracturl;

    /**
     * 
     * 表字段 : ec_online_sign.attorneyURL
     */
    private String attorneyurl;

    /**
     * 
     * 表字段 : ec_online_sign.bankAccountName
     */
    private String bankaccountname;

    /**
     * 
     * 表字段 : ec_online_sign.bankAccountBank
     */
    private String bankaccountbank;

    /**
     * 
     * 表字段 : ec_online_sign.bankAccountAccount
     */
    private String bankaccountaccount;

    /**
     * 审核状态：0为待审核，1为审核通过，2为审核不通过，3为待重审
     * 表字段 : ec_online_sign.examineStatus
     */
    private Integer examinestatus;

    /**
     * 提交时间
     * 表字段 : ec_online_sign.submitTime
     */
    private Date submittime;

    /**
     * 
     * 表字段 : ec_online_sign.examiner
     */
    private String examiner;

    /**
     * 申请人
     * 表字段 : ec_online_sign.applicant
     */
    private String applicant;

    /**
     * 商务经理id
     * 表字段 : ec_online_sign.businessManagerid
     */
    private Integer businessmanagerid;

    /**
     * 
     * 表字段 : ec_online_sign.busid
     */
    private Long busid;

    /**
     * 
     * 表字段 : ec_online_sign.adminid
     */
    private Integer adminid;

    /**
     * 关联商家管理后台shopid
     * 表字段 : ec_online_sign.shopid
     */
    private Long shopid;

    /**
     * 餐厅坐标系（火星）
     * 表字段 : ec_online_sign.coordinate
     */
    private String coordinate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ec_online_sign
     *
     * @mbg.generated Wed Sep 06 11:55:54 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键ID 字段:ec_online_sign.id
     *
     * @return ec_online_sign.id, 主键ID
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键ID 字段:ec_online_sign.id
     *
     * @param id the value for ec_online_sign.id, 主键ID
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 合作方式，佣金收取比例 字段:ec_online_sign.cooperateType
     *
     * @return ec_online_sign.cooperateType, 合作方式，佣金收取比例
     */
    public String getCooperatetype() {
        return cooperatetype;
    }

    /**
     * 设置 合作方式，佣金收取比例 字段:ec_online_sign.cooperateType
     *
     * @param cooperatetype the value for ec_online_sign.cooperateType, 合作方式，佣金收取比例
     */
    public void setCooperatetype(String cooperatetype) {
        this.cooperatetype = cooperatetype == null ? null : cooperatetype.trim();
    }

    /**
     * 获取 餐厅名字 字段:ec_online_sign.restaurantName
     *
     * @return ec_online_sign.restaurantName, 餐厅名字
     */
    public String getRestaurantname() {
        return restaurantname;
    }

    /**
     * 设置 餐厅名字 字段:ec_online_sign.restaurantName
     *
     * @param restaurantname the value for ec_online_sign.restaurantName, 餐厅名字
     */
    public void setRestaurantname(String restaurantname) {
        this.restaurantname = restaurantname == null ? null : restaurantname.trim();
    }

    /**
     * 获取 餐厅类别 字段:ec_online_sign.restaurantType
     *
     * @return ec_online_sign.restaurantType, 餐厅类别
     */
    public String getRestauranttype() {
        return restauranttype;
    }

    /**
     * 设置 餐厅类别 字段:ec_online_sign.restaurantType
     *
     * @param restauranttype the value for ec_online_sign.restaurantType, 餐厅类别
     */
    public void setRestauranttype(String restauranttype) {
        this.restauranttype = restauranttype == null ? null : restauranttype.trim();
    }

    /**
     * 获取 餐厅所在省 字段:ec_online_sign.restaurantProvince
     *
     * @return ec_online_sign.restaurantProvince, 餐厅所在省
     */
    public String getRestaurantprovince() {
        return restaurantprovince;
    }

    /**
     * 设置 餐厅所在省 字段:ec_online_sign.restaurantProvince
     *
     * @param restaurantprovince the value for ec_online_sign.restaurantProvince, 餐厅所在省
     */
    public void setRestaurantprovince(String restaurantprovince) {
        this.restaurantprovince = restaurantprovince == null ? null : restaurantprovince.trim();
    }

    /**
     * 获取 餐厅所在城市 字段:ec_online_sign.restaurantCity
     *
     * @return ec_online_sign.restaurantCity, 餐厅所在城市
     */
    public String getRestaurantcity() {
        return restaurantcity;
    }

    /**
     * 设置 餐厅所在城市 字段:ec_online_sign.restaurantCity
     *
     * @param restaurantcity the value for ec_online_sign.restaurantCity, 餐厅所在城市
     */
    public void setRestaurantcity(String restaurantcity) {
        this.restaurantcity = restaurantcity == null ? null : restaurantcity.trim();
    }

    /**
     * 获取 餐厅所在区 字段:ec_online_sign.restaurantDistrict
     *
     * @return ec_online_sign.restaurantDistrict, 餐厅所在区
     */
    public String getRestaurantdistrict() {
        return restaurantdistrict;
    }

    /**
     * 设置 餐厅所在区 字段:ec_online_sign.restaurantDistrict
     *
     * @param restaurantdistrict the value for ec_online_sign.restaurantDistrict, 餐厅所在区
     */
    public void setRestaurantdistrict(String restaurantdistrict) {
        this.restaurantdistrict = restaurantdistrict == null ? null : restaurantdistrict.trim();
    }

    /**
     * 获取 餐厅所在街道 字段:ec_online_sign.restaurantStreet
     *
     * @return ec_online_sign.restaurantStreet, 餐厅所在街道
     */
    public String getRestaurantstreet() {
        return restaurantstreet;
    }

    /**
     * 设置 餐厅所在街道 字段:ec_online_sign.restaurantStreet
     *
     * @param restaurantstreet the value for ec_online_sign.restaurantStreet, 餐厅所在街道
     */
    public void setRestaurantstreet(String restaurantstreet) {
        this.restaurantstreet = restaurantstreet == null ? null : restaurantstreet.trim();
    }

    /**
     * 获取 餐厅所在详细地址 字段:ec_online_sign.restaurantAddress
     *
     * @return ec_online_sign.restaurantAddress, 餐厅所在详细地址
     */
    public String getRestaurantaddress() {
        return restaurantaddress;
    }

    /**
     * 设置 餐厅所在详细地址 字段:ec_online_sign.restaurantAddress
     *
     * @param restaurantaddress the value for ec_online_sign.restaurantAddress, 餐厅所在详细地址
     */
    public void setRestaurantaddress(String restaurantaddress) {
        this.restaurantaddress = restaurantaddress == null ? null : restaurantaddress.trim();
    }

    /**
     * 获取 餐厅电话 字段:ec_online_sign.restaurantTel
     *
     * @return ec_online_sign.restaurantTel, 餐厅电话
     */
    public String getRestauranttel() {
        return restauranttel;
    }

    /**
     * 设置 餐厅电话 字段:ec_online_sign.restaurantTel
     *
     * @param restauranttel the value for ec_online_sign.restaurantTel, 餐厅电话
     */
    public void setRestauranttel(String restauranttel) {
        this.restauranttel = restauranttel == null ? null : restauranttel.trim();
    }

    /**
     * 获取  字段:ec_online_sign.restaurantOpenTime
     *
     * @return ec_online_sign.restaurantOpenTime, 
     */
    public String getRestaurantopentime() {
        return restaurantopentime;
    }

    /**
     * 设置  字段:ec_online_sign.restaurantOpenTime
     *
     * @param restaurantopentime the value for ec_online_sign.restaurantOpenTime, 
     */
    public void setRestaurantopentime(String restaurantopentime) {
        this.restaurantopentime = restaurantopentime == null ? null : restaurantopentime.trim();
    }

    /**
     * 获取  字段:ec_online_sign.restaurantCloseTime
     *
     * @return ec_online_sign.restaurantCloseTime, 
     */
    public String getRestaurantclosetime() {
        return restaurantclosetime;
    }

    /**
     * 设置  字段:ec_online_sign.restaurantCloseTime
     *
     * @param restaurantclosetime the value for ec_online_sign.restaurantCloseTime, 
     */
    public void setRestaurantclosetime(String restaurantclosetime) {
        this.restaurantclosetime = restaurantclosetime == null ? null : restaurantclosetime.trim();
    }

    /**
     * 获取  字段:ec_online_sign.restaurantIndroduction
     *
     * @return ec_online_sign.restaurantIndroduction, 
     */
    public String getRestaurantindroduction() {
        return restaurantindroduction;
    }

    /**
     * 设置  字段:ec_online_sign.restaurantIndroduction
     *
     * @param restaurantindroduction the value for ec_online_sign.restaurantIndroduction, 
     */
    public void setRestaurantindroduction(String restaurantindroduction) {
        this.restaurantindroduction = restaurantindroduction == null ? null : restaurantindroduction.trim();
    }

    /**
     * 获取  字段:ec_online_sign.managerPhone
     *
     * @return ec_online_sign.managerPhone, 
     */
    public String getManagerphone() {
        return managerphone;
    }

    /**
     * 设置  字段:ec_online_sign.managerPhone
     *
     * @param managerphone the value for ec_online_sign.managerPhone, 
     */
    public void setManagerphone(String managerphone) {
        this.managerphone = managerphone == null ? null : managerphone.trim();
    }

    /**
     * 获取  字段:ec_online_sign.bossPhone
     *
     * @return ec_online_sign.bossPhone, 
     */
    public String getBossphone() {
        return bossphone;
    }

    /**
     * 设置  字段:ec_online_sign.bossPhone
     *
     * @param bossphone the value for ec_online_sign.bossPhone, 
     */
    public void setBossphone(String bossphone) {
        this.bossphone = bossphone == null ? null : bossphone.trim();
    }

    /**
     * 获取 法人身份证号码 字段:ec_online_sign.artificialPersonID
     *
     * @return ec_online_sign.artificialPersonID, 法人身份证号码
     */
    public String getArtificialpersonid() {
        return artificialpersonid;
    }

    /**
     * 设置 法人身份证号码 字段:ec_online_sign.artificialPersonID
     *
     * @param artificialpersonid the value for ec_online_sign.artificialPersonID, 法人身份证号码
     */
    public void setArtificialpersonid(String artificialpersonid) {
        this.artificialpersonid = artificialpersonid == null ? null : artificialpersonid.trim();
    }

    /**
     * 获取 法人名字 字段:ec_online_sign.artificialPersonName
     *
     * @return ec_online_sign.artificialPersonName, 法人名字
     */
    public String getArtificialpersonname() {
        return artificialpersonname;
    }

    /**
     * 设置 法人名字 字段:ec_online_sign.artificialPersonName
     *
     * @param artificialpersonname the value for ec_online_sign.artificialPersonName, 法人名字
     */
    public void setArtificialpersonname(String artificialpersonname) {
        this.artificialpersonname = artificialpersonname == null ? null : artificialpersonname.trim();
    }

    /**
     * 获取  字段:ec_online_sign.contractID
     *
     * @return ec_online_sign.contractID, 
     */
    public String getContractid() {
        return contractid;
    }

    /**
     * 设置  字段:ec_online_sign.contractID
     *
     * @param contractid the value for ec_online_sign.contractID, 
     */
    public void setContractid(String contractid) {
        this.contractid = contractid == null ? null : contractid.trim();
    }

    /**
     * 获取  字段:ec_online_sign.contractName
     *
     * @return ec_online_sign.contractName, 
     */
    public String getContractname() {
        return contractname;
    }

    /**
     * 设置  字段:ec_online_sign.contractName
     *
     * @param contractname the value for ec_online_sign.contractName, 
     */
    public void setContractname(String contractname) {
        this.contractname = contractname == null ? null : contractname.trim();
    }

    /**
     * 获取  字段:ec_online_sign.licenseID
     *
     * @return ec_online_sign.licenseID, 
     */
    public String getLicenseid() {
        return licenseid;
    }

    /**
     * 设置  字段:ec_online_sign.licenseID
     *
     * @param licenseid the value for ec_online_sign.licenseID, 
     */
    public void setLicenseid(String licenseid) {
        this.licenseid = licenseid == null ? null : licenseid.trim();
    }

    /**
     * 获取  字段:ec_online_sign.licenseName
     *
     * @return ec_online_sign.licenseName, 
     */
    public String getLicensename() {
        return licensename;
    }

    /**
     * 设置  字段:ec_online_sign.licenseName
     *
     * @param licensename the value for ec_online_sign.licenseName, 
     */
    public void setLicensename(String licensename) {
        this.licensename = licensename == null ? null : licensename.trim();
    }

    /**
     * 获取 存放图片文件夹 字段:ec_online_sign.baseURL
     *
     * @return ec_online_sign.baseURL, 存放图片文件夹
     */
    public String getBaseurl() {
        return baseurl;
    }

    /**
     * 设置 存放图片文件夹 字段:ec_online_sign.baseURL
     *
     * @param baseurl the value for ec_online_sign.baseURL, 存放图片文件夹
     */
    public void setBaseurl(String baseurl) {
        this.baseurl = baseurl == null ? null : baseurl.trim();
    }

    /**
     * 获取 餐厅图片 字段:ec_online_sign.viewURL
     *
     * @return ec_online_sign.viewURL, 餐厅图片
     */
    public String getViewurl() {
        return viewurl;
    }

    /**
     * 设置 餐厅图片 字段:ec_online_sign.viewURL
     *
     * @param viewurl the value for ec_online_sign.viewURL, 餐厅图片
     */
    public void setViewurl(String viewurl) {
        this.viewurl = viewurl == null ? null : viewurl.trim();
    }

    /**
     * 获取 法人图片地址 字段:ec_online_sign.artificialPersonURL
     *
     * @return ec_online_sign.artificialPersonURL, 法人图片地址
     */
    public String getArtificialpersonurl() {
        return artificialpersonurl;
    }

    /**
     * 设置 法人图片地址 字段:ec_online_sign.artificialPersonURL
     *
     * @param artificialpersonurl the value for ec_online_sign.artificialPersonURL, 法人图片地址
     */
    public void setArtificialpersonurl(String artificialpersonurl) {
        this.artificialpersonurl = artificialpersonurl == null ? null : artificialpersonurl.trim();
    }

    /**
     * 获取  字段:ec_online_sign.licenseURL
     *
     * @return ec_online_sign.licenseURL, 
     */
    public String getLicenseurl() {
        return licenseurl;
    }

    /**
     * 设置  字段:ec_online_sign.licenseURL
     *
     * @param licenseurl the value for ec_online_sign.licenseURL, 
     */
    public void setLicenseurl(String licenseurl) {
        this.licenseurl = licenseurl == null ? null : licenseurl.trim();
    }

    /**
     * 获取  字段:ec_online_sign.contractURL
     *
     * @return ec_online_sign.contractURL, 
     */
    public String getContracturl() {
        return contracturl;
    }

    /**
     * 设置  字段:ec_online_sign.contractURL
     *
     * @param contracturl the value for ec_online_sign.contractURL, 
     */
    public void setContracturl(String contracturl) {
        this.contracturl = contracturl == null ? null : contracturl.trim();
    }

    /**
     * 获取  字段:ec_online_sign.attorneyURL
     *
     * @return ec_online_sign.attorneyURL, 
     */
    public String getAttorneyurl() {
        return attorneyurl;
    }

    /**
     * 设置  字段:ec_online_sign.attorneyURL
     *
     * @param attorneyurl the value for ec_online_sign.attorneyURL, 
     */
    public void setAttorneyurl(String attorneyurl) {
        this.attorneyurl = attorneyurl == null ? null : attorneyurl.trim();
    }

    /**
     * 获取  字段:ec_online_sign.bankAccountName
     *
     * @return ec_online_sign.bankAccountName, 
     */
    public String getBankaccountname() {
        return bankaccountname;
    }

    /**
     * 设置  字段:ec_online_sign.bankAccountName
     *
     * @param bankaccountname the value for ec_online_sign.bankAccountName, 
     */
    public void setBankaccountname(String bankaccountname) {
        this.bankaccountname = bankaccountname == null ? null : bankaccountname.trim();
    }

    /**
     * 获取  字段:ec_online_sign.bankAccountBank
     *
     * @return ec_online_sign.bankAccountBank, 
     */
    public String getBankaccountbank() {
        return bankaccountbank;
    }

    /**
     * 设置  字段:ec_online_sign.bankAccountBank
     *
     * @param bankaccountbank the value for ec_online_sign.bankAccountBank, 
     */
    public void setBankaccountbank(String bankaccountbank) {
        this.bankaccountbank = bankaccountbank == null ? null : bankaccountbank.trim();
    }

    /**
     * 获取  字段:ec_online_sign.bankAccountAccount
     *
     * @return ec_online_sign.bankAccountAccount, 
     */
    public String getBankaccountaccount() {
        return bankaccountaccount;
    }

    /**
     * 设置  字段:ec_online_sign.bankAccountAccount
     *
     * @param bankaccountaccount the value for ec_online_sign.bankAccountAccount, 
     */
    public void setBankaccountaccount(String bankaccountaccount) {
        this.bankaccountaccount = bankaccountaccount == null ? null : bankaccountaccount.trim();
    }

    /**
     * 获取 审核状态：0为待审核，1为审核通过，2为审核不通过，3为待重审 字段:ec_online_sign.examineStatus
     *
     * @return ec_online_sign.examineStatus, 审核状态：0为待审核，1为审核通过，2为审核不通过，3为待重审
     */
    public Integer getExaminestatus() {
        return examinestatus;
    }

    /**
     * 设置 审核状态：0为待审核，1为审核通过，2为审核不通过，3为待重审 字段:ec_online_sign.examineStatus
     *
     * @param examinestatus the value for ec_online_sign.examineStatus, 审核状态：0为待审核，1为审核通过，2为审核不通过，3为待重审
     */
    public void setExaminestatus(Integer examinestatus) {
        this.examinestatus = examinestatus;
    }

    /**
     * 获取 提交时间 字段:ec_online_sign.submitTime
     *
     * @return ec_online_sign.submitTime, 提交时间
     */
    public Date getSubmittime() {
        return submittime;
    }

    /**
     * 设置 提交时间 字段:ec_online_sign.submitTime
     *
     * @param submittime the value for ec_online_sign.submitTime, 提交时间
     */
    public void setSubmittime(Date submittime) {
        this.submittime = submittime;
    }

    /**
     * 获取  字段:ec_online_sign.examiner
     *
     * @return ec_online_sign.examiner, 
     */
    public String getExaminer() {
        return examiner;
    }

    /**
     * 设置  字段:ec_online_sign.examiner
     *
     * @param examiner the value for ec_online_sign.examiner, 
     */
    public void setExaminer(String examiner) {
        this.examiner = examiner == null ? null : examiner.trim();
    }

    /**
     * 获取 申请人 字段:ec_online_sign.applicant
     *
     * @return ec_online_sign.applicant, 申请人
     */
    public String getApplicant() {
        return applicant;
    }

    /**
     * 设置 申请人 字段:ec_online_sign.applicant
     *
     * @param applicant the value for ec_online_sign.applicant, 申请人
     */
    public void setApplicant(String applicant) {
        this.applicant = applicant == null ? null : applicant.trim();
    }

    /**
     * 获取 商务经理id 字段:ec_online_sign.businessManagerid
     *
     * @return ec_online_sign.businessManagerid, 商务经理id
     */
    public Integer getBusinessmanagerid() {
        return businessmanagerid;
    }

    /**
     * 设置 商务经理id 字段:ec_online_sign.businessManagerid
     *
     * @param businessmanagerid the value for ec_online_sign.businessManagerid, 商务经理id
     */
    public void setBusinessmanagerid(Integer businessmanagerid) {
        this.businessmanagerid = businessmanagerid;
    }

    /**
     * 获取  字段:ec_online_sign.busid
     *
     * @return ec_online_sign.busid, 
     */
    public Long getBusid() {
        return busid;
    }

    /**
     * 设置  字段:ec_online_sign.busid
     *
     * @param busid the value for ec_online_sign.busid, 
     */
    public void setBusid(Long busid) {
        this.busid = busid;
    }

    /**
     * 获取  字段:ec_online_sign.adminid
     *
     * @return ec_online_sign.adminid, 
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * 设置  字段:ec_online_sign.adminid
     *
     * @param adminid the value for ec_online_sign.adminid, 
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * 获取 关联商家管理后台shopid 字段:ec_online_sign.shopid
     *
     * @return ec_online_sign.shopid, 关联商家管理后台shopid
     */
    public Long getShopid() {
        return shopid;
    }

    /**
     * 设置 关联商家管理后台shopid 字段:ec_online_sign.shopid
     *
     * @param shopid the value for ec_online_sign.shopid, 关联商家管理后台shopid
     */
    public void setShopid(Long shopid) {
        this.shopid = shopid;
    }

    /**
     * 获取 餐厅坐标系（火星） 字段:ec_online_sign.coordinate
     *
     * @return ec_online_sign.coordinate, 餐厅坐标系（火星）
     */
    public String getCoordinate() {
        return coordinate;
    }

    /**
     * 设置 餐厅坐标系（火星） 字段:ec_online_sign.coordinate
     *
     * @param coordinate the value for ec_online_sign.coordinate, 餐厅坐标系（火星）
     */
    public void setCoordinate(String coordinate) {
        this.coordinate = coordinate == null ? null : coordinate.trim();
    }
}